config/routes.rb
Gbay::Application.routes.draw do
  devise_for :users
  resources :items
  resources :comments
  root 'items#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, :all
    can :new, Item
    can :update, Item do |item|
      item.try(:user) == user
    end
    can :destroy, Item do |item|
      item.try(:user) == user
    end
    if user.user_role? "admin"
      can :manage, :all
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :item

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def user_role? role
    if self.role == role
      return true
    end
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #include Authentication
  #protect_from_forgery
  #rescue_from CanCan: :AccessDenied do |exception|
  #  flash[:error] = "Access denied."
  #  redirect_to root_url
  #end
  before_action :authenticate_user!

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  respond_to :html
  def show
    respond_with(@comment)
  end

  def index
    @comments=Comment.all
  end

  def create
    @comment.user_id = current_user.id
    @comment.save
    respond_with(@comment)
  end

  def update
    @comment.update!(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id, :item_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource

  respond_to :html

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def create
    @item.user_id = current_user.id
    @item.save
    respond_with(@item)
  end

  def update
    @item.update!(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :Price, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
    <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_field :content %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
    <div class="field">
      <%= f.hidden_field :item_id, :value => item.id %>
    </div>
<% end %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.html.erb
<h1>Listing items</h1>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Price %><br>
    <%= f.number_field :Price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.Price %></td>
        <td><%= link_to 'Show', item %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price: $</strong>
  <%=@item.Price %>
</p>
<p>
  <strong>User:</strong>
  <%= @item.user.email %>
</p>

<br>
<br>
<table>
  <thead>
  <tr>
    <th>Author</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @item.comments.each do |comment| %>
      <tr>
        <td><%= comment.user.email %></td>
        <td><%= comment.content %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<%if can? :read, @item%>
    <%= link_to 'Comment', new_comment_path %>
<%end%>
<%if can? :update, @item%>
    <%= link_to 'Edit', edit_item_path(@item) %>
<%end%>
<% if can? :destroy, @item %>
    <%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gbay</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>
<% if user_signed_in?%>
    <li><%= link_to "Sign-out", destroy_user_session_path, :method => :delete, class: "nav-item" %></li>
<% else %>
    <li><%= link_to "Sign-in", new_user_session_path %>
<% end %>
</body>
</html>